# Generated by Django 5.2.5 on 2025-09-08 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('max_file_size', models.BigIntegerField(default=52428800)),
                ('allowed_file_types', models.JSONField(default=list)),
                ('require_password', models.BooleanField(default=False)),
                ('password_min_length', models.IntegerField(default=8)),
                ('auto_expire_days', models.IntegerField(blank=True, null=True)),
                ('max_access_count', models.IntegerField(blank=True, null=True)),
                ('enable_watermark', models.BooleanField(default=False)),
                ('watermark_template', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('document_id', models.IntegerField()),
                ('action', models.CharField(choices=[('view', 'Document Viewed'), ('download', 'Document Downloaded'), ('decrypt', 'Document Decrypted'), ('password_attempt', 'Password Attempt'), ('failed_access', 'Failed Access')], max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField()),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EncryptedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='encrypted_documents/original/')),
                ('encrypted_file', models.FileField(upload_to='encrypted_documents/encrypted/')),
                ('encryption_key', models.CharField(max_length=256)),
                ('file_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordProtectedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='protected_documents/original/')),
                ('protected_file', models.FileField(upload_to='protected_documents/protected/')),
                ('password_hash', models.CharField(max_length=128)),
                ('protection_type', models.CharField(choices=[('view', 'View Protection'), ('edit', 'Edit Protection'), ('print', 'Print Protection'), ('copy', 'Copy Protection'), ('full', 'Full Protection')], max_length=10)),
                ('access_count', models.IntegerField(default=0)),
                ('max_access_count', models.IntegerField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatermarkSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='watermarked_documents/')),
                ('watermark_text', models.CharField(max_length=200)),
                ('watermark_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('user_info', 'User Info')], default='text', max_length=20)),
                ('transparency', models.FloatField(default=0.3)),
                ('position', models.CharField(choices=[('center', 'Center'), ('top_left', 'Top Left'), ('top_right', 'Top Right'), ('bottom_left', 'Bottom Left'), ('bottom_right', 'Bottom Right')], default='center', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
