# Generated by Django 5.2.5 on 2025-09-08 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('operation_type', models.CharField(choices=[('organize', 'Organize Files'), ('rename', 'Rename Files'), ('move', 'Move Files'), ('copy', 'Copy Files'), ('delete', 'Delete Files'), ('compress', 'Compress Files'), ('extract', 'Extract Archives')], max_length=20)),
                ('source_paths', models.JSONField(default=list)),
                ('target_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('files_processed', models.IntegerField(default=0)),
                ('total_files', models.IntegerField(default=0)),
                ('operation_log', models.JSONField(default=list)),
                ('error_log', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_path', models.CharField(max_length=1000)),
                ('new_path', models.CharField(blank=True, max_length=1000)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('file_extension', models.CharField(max_length=10)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_status', models.CharField(default='pending', max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('batch_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='batch_organizer.batchoperation')),
            ],
            options={
                'ordering': ['file_name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('extension', 'By File Extension'), ('size', 'By File Size'), ('date_created', 'By Creation Date'), ('date_modified', 'By Modification Date'), ('name_pattern', 'By Name Pattern'), ('content_type', 'By Content Type'), ('custom', 'Custom Rule')], max_length=20)),
                ('rule_criteria', models.JSONField(default=dict)),
                ('target_folder', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rules', models.ManyToManyField(to='batch_organizer.organizationrule')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='batchoperation',
            name='rules',
            field=models.ManyToManyField(blank=True, to='batch_organizer.organizationrule'),
        ),
    ]
