# Generated by Django 5.2.5 on 2025-08-15 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFOperationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('merge', 'Merge PDF'), ('split', 'Split PDF'), ('pdf_to_image', 'PDF to Image')], max_length=20)),
                ('file_count', models.IntegerField()),
                ('total_size', models.BigIntegerField()),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
