# Generated by Django 5.2.5 on 2025-09-08 00:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactQR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('organization', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QRCodeJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('generate_text', 'Generate QR from Text'), ('generate_url', 'Generate QR from URL'), ('generate_contact', 'Generate QR from Contact'), ('read_qr', 'Read QR Code'), ('batch_generate', 'Batch Generate QR')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('qr_content', models.TextField()),
                ('qr_size', models.IntegerField(default=200)),
                ('qr_error_correction', models.CharField(default='M', max_length=1)),
                ('output_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('output_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
