# Generated by Django 5.2.5 on 2025-09-07 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundRemovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('output_filename', models.CharField(max_length=255)),
                ('file_size_before', models.IntegerField()),
                ('file_size_after', models.IntegerField()),
                ('processing_time', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageEnhancementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('output_filename', models.CharField(max_length=255)),
                ('enhancement_type', models.CharField(choices=[('sharpen', 'Sharpen'), ('denoise', 'Denoise'), ('upscale', 'Upscale'), ('color_enhance', 'Color Enhancement'), ('brightness', 'Brightness Adjustment'), ('contrast', 'Contrast Adjustment')], max_length=20)),
                ('settings_used', models.JSONField(default=dict)),
                ('file_size_before', models.IntegerField()),
                ('file_size_after', models.IntegerField()),
                ('processing_time', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
