# Generated by Django 5.2.5 on 2025-09-08 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('icon', 'Icon'), ('illustration', 'Illustration'), ('photo', 'Photo'), ('pattern', 'Pattern'), ('texture', 'Texture'), ('background', 'Background')], max_length=20)),
                ('file', models.FileField(upload_to='design_assets/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='asset_thumbnails/')),
                ('tags', models.JSONField(default=list)),
                ('license_type', models.CharField(default='free', max_length=50)),
                ('download_count', models.IntegerField(default=0)),
                ('file_size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-download_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FontFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('font_file', models.FileField(upload_to='fonts/')),
                ('font_type', models.CharField(choices=[('ttf', 'TrueType'), ('otf', 'OpenType'), ('woff', 'Web Font')], default='ttf', max_length=10)),
                ('is_web_safe', models.BooleanField(default=False)),
                ('preview_text', models.CharField(default='The quick brown fox', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('colors', models.JSONField(default=list)),
                ('is_predefined', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DesignProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('project_type', models.CharField(choices=[('flyer', 'Flyer'), ('poster', 'Poster'), ('brochure', 'Brochure'), ('business_card', 'Business Card'), ('letterhead', 'Letterhead'), ('certificate', 'Certificate'), ('invitation', 'Invitation'), ('custom', 'Custom Design')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('canvas_width', models.IntegerField(default=800)),
                ('canvas_height', models.IntegerField(default=600)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('design_data', models.JSONField(default=dict)),
                ('preview_image', models.ImageField(blank=True, upload_to='design_previews/')),
                ('final_document', models.FileField(blank=True, upload_to='final_designs/')),
                ('is_template', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('shape', 'Shape'), ('line', 'Line'), ('chart', 'Chart'), ('table', 'Table'), ('qr_code', 'QR Code'), ('barcode', 'Barcode')], max_length=20)),
                ('element_data', models.JSONField(default=dict)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('width', models.FloatField(default=100)),
                ('height', models.FloatField(default=50)),
                ('rotation', models.FloatField(default=0)),
                ('opacity', models.FloatField(default=1.0)),
                ('z_index', models.IntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='visual_designer.designproject')),
            ],
            options={
                'ordering': ['z_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='template_thumbnails/')),
                ('template_data', models.JSONField(default=dict)),
                ('tags', models.JSONField(default=list)),
                ('is_premium', models.BooleanField(default=False)),
                ('download_count', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-download_count', '-rating'],
            },
        ),
    ]
