# Generated by Django 5.2.5 on 2025-09-08 00:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signature_name', models.CharField(max_length=100)),
                ('signature_image_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WatermarkJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('text_watermark', 'Text Watermark'), ('image_watermark', 'Image Watermark'), ('remove_watermark', 'Remove Watermark')], max_length=20)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF Document'), ('image', 'Image File')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('input_filename', models.CharField(max_length=255)),
                ('input_file_path', models.CharField(max_length=500)),
                ('input_file_size', models.IntegerField()),
                ('watermark_text', models.TextField(blank=True, null=True)),
                ('watermark_position', models.CharField(default='bottom-right', max_length=20)),
                ('watermark_opacity', models.FloatField(default=0.3)),
                ('watermark_font_size', models.IntegerField(default=12)),
                ('watermark_color', models.CharField(default='#000000', max_length=7)),
                ('output_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('output_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
