# Generated by Django 5.2.5 on 2025-08-15 19:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compression', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileProcessingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('image_compress', 'Image Compression'), ('pdf_compress', 'PDF Compression'), ('youtube_convert', 'YouTube Conversion'), ('pdf_merge', 'PDF Merge'), ('pdf_split', 'PDF Split'), ('pdf_to_image', 'PDF to Image'), ('image_to_pdf', 'Image to PDF')], max_length=20)),
                ('file_size_before', models.BigIntegerField(help_text='Size in bytes')),
                ('file_size_after', models.BigIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'file_processing_stats',
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_stats',
            },
        ),
    ]
