# Generated by Django 4.2.7 on 2025-08-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('format', models.CharField(choices=[('mp3', 'MP3 Audio'), ('mp4', 'MP4 Video')], max_length=4)),
                ('file_size', models.BigIntegerField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
