# Generated by Django 5.2.5 on 2025-09-08 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('document_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('parsing_rules', models.JSONField(default=dict)),
                ('field_mappings', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('entity_type', models.CharField(max_length=50)),
                ('validation_pattern', models.CharField(max_length=500)),
                ('error_message', models.CharField(max_length=200)),
                ('is_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParsedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='parsed_documents/original/')),
                ('document_type', models.CharField(choices=[('pdf', 'PDF Document'), ('docx', 'Word Document'), ('txt', 'Text File'), ('csv', 'CSV File'), ('xlsx', 'Excel File'), ('image', 'Image with Text')], max_length=20)),
                ('extracted_text', models.TextField()),
                ('extracted_data', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('processing_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntityExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('person', 'Person Name'), ('organization', 'Organization'), ('location', 'Location'), ('date', 'Date'), ('phone', 'Phone Number'), ('email', 'Email Address'), ('money', 'Money Amount'), ('custom', 'Custom Entity')], max_length=20)),
                ('entity_value', models.CharField(max_length=500)),
                ('confidence', models.FloatField(default=0.0)),
                ('start_position', models.IntegerField()),
                ('end_position', models.IntegerField()),
                ('context', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='document_parser.parseddocument')),
            ],
            options={
                'ordering': ['start_position'],
            },
        ),
        migrations.CreateModel(
            name='TextExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(default=1)),
                ('text_content', models.TextField()),
                ('bounding_boxes', models.JSONField(default=list)),
                ('language_detected', models.CharField(default='en', max_length=10)),
                ('extraction_method', models.CharField(choices=[('ocr', 'OCR'), ('text_layer', 'Text Layer'), ('parsing', 'Document Parsing')], default='parsing', max_length=20)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='document_parser.parseddocument')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
    ]
