# Generated by Django 5.2.5 on 2025-08-15 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageOperationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('images_to_pdf', 'Images to PDF')], max_length=20)),
                ('image_count', models.IntegerField()),
                ('total_size', models.BigIntegerField()),
                ('page_size', models.CharField(default='A4', max_length=10)),
                ('orientation', models.CharField(default='portrait', max_length=10)),
                ('quality', models.CharField(default='high', max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
