# Generated by Django 5.2.5 on 2025-09-08 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('template_type', models.CharField(choices=[('letter', 'Business Letter'), ('invoice', 'Invoice'), ('resume', 'Resume'), ('report', 'Report'), ('contract', 'Contract'), ('newsletter', 'Newsletter'), ('certificate', 'Certificate'), ('custom', 'Custom Template')], max_length=20)),
                ('content_structure', models.JSONField(default=dict)),
                ('preview_image', models.ImageField(blank=True, upload_to='template_previews/')),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_file', models.FileField(upload_to='generated_documents/')),
                ('field_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template_builder.documenttemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text Field'), ('textarea', 'Text Area'), ('date', 'Date Field'), ('number', 'Number Field'), ('image', 'Image Field'), ('signature', 'Signature Field'), ('table', 'Table Field'), ('list', 'List Field')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.TextField(blank=True)),
                ('placeholder_text', models.CharField(blank=True, max_length=200)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('width', models.FloatField(default=100)),
                ('height', models.FloatField(default=30)),
                ('font_size', models.IntegerField(default=12)),
                ('font_family', models.CharField(default='Arial', max_length=50)),
                ('text_color', models.CharField(default='#000000', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='template_builder.documenttemplate')),
            ],
            options={
                'ordering': ['order', 'field_name'],
            },
        ),
    ]
